### ISSUE TITLE
Receipt problems. Need help.

### ISSUE THREAD

**Issue by toddfreese** [MugunthKumar/MKStoreKit#217]
I am getting these warnings on app startup. Any idea on what is causing this?

2015-01-25 12:58:51.098 ShotBOT[2752:1087107] No receipt exists. Try refreshing the reciept payload. If this issue persists it is likely the app is not authentic.
2015-01-25 12:58:51.103 ShotBOT[2752:1087107] Receipt validation failed with error: Error Domain=com.mugunthkumar.mkstorekit Code=21009 "The reciept does not exist." UserInfo=0x14dea340 {NSLocalizedDescription=The reciept does not exist.}
2015-01-25 12:58:52.899 ShotBOT[2752:1087107] Receipt request completed but there is no receipt. The user may have refused to login, or the reciept is missing.

**Comment by MugunthKumar** [comment]
Fixed

**Comment by toddfreese** [comment]
I updated from master and I am still getting the messages. Any thoughts?

**Comment by leebarringer** [comment]
Hello, hope you don't mind me commenting. I had the same problem today and was also using the latest master too with the fix above. Found a solution that worked for me.

I took a look at the .m file and noticed that just before the receipt request is made there is a conditional statement to determine if you are in debug mode. If you are, the code sends the receipt verification to the sandbox server, if not then to the live server. Are you operating Xcode in debug? I temporarily commented out the "else if" and hardwired a call to the sandbox.

//#ifdef DEBUG
  NSMutableURLRequest *storeRequest = [NSMutableURLRequest requestWithURL:[NSURL URLWithString:kSandboxServer]];
//#else
  //NSMutableURLRequest *storeRequest = [NSMutableURLRequest requestWithURL:[NSURL URLWithString:kLiveServer]];
//#endif
